### PR TITLE
Change faq section to use details

### PR DESCRIPTION
**Pull request by Meep3692**
The faq section now makes use of the details element which allows it to work well on systems which lack js or css capabilities.
In its current state, there is an animation, implemented entirely in css, for the faq panel opening, however I'm not sure it's feasible to create an animation for it closing while maintaining good support for systems lacking css and javascript.
In this branch, faq.js has been removed completely as I didn't end up having any use for javascript in the faq section.

### CODE REVIEW

**Comment by Meep3692** [comment]
Some of the indents in _faq.scss are janky

**Review by MathyouMB — COMMENTED** [review]
This is great! Definitely good to remove the JQuery script. 

Is there anyway you could have it also animate when you close an faq section?

**Comment by Meep3692** [comment]
At first I didn't think this was possible as the element is immediately vanished when you click the summary, but of course javascript's event.preventDefault() is here to save the day. I've created a small prototype which I'm going to start integrating into the site now

**Review by MathyouMB — APPROVED** [review]
This seems to work great! Seems a lot less flaky than the previous implementation. 

You mentioned this is a prototype, so I wont merge in case you want to format a bit, but otherwise I'm happy to merge this.

**Comment by Meep3692** [comment]
Sorry, I meant I had created a separate prototype to see if it was possible. I'm fine with this merging if you are.

**Pull request merged**
